[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 7.0

[window]
decorations = "None"
padding = { x = 4, y = 4 }
opacity = 0.80

[cursor]
style = { shape = "Block" }

[colors.primary]
background = "#000000"
foreground = "#00ff00"

[colors.normal]
black =   "#000000"
red =     "#ff0000"
green =   "#00ff00"
yellow =  "#ffff00"
blue =    "#0000ff"
magenta = "#ff00ff"
cyan =    "#00ffff"
white =   "#ffffff"

[colors.bright]
black =   "#555555"
red =     "#ff5555"
green =   "#55ff55"
yellow =  "#ffff55"
blue =    "#5555ff"
magenta = "#ff55ff"
cyan =    "#55ffff"
white =   "#ffffff"

[mouse]
hide_when_typing = true
